// <auto-generated />
#pragma warning disable CS0105
using MasterMemory.Validation;
using MasterMemory;
using MessagePack;
using System.Collections.Generic;
using System;

namespace Example.Tables
{
   public sealed partial class StageMasterTable : TableBase<StageMaster>, ITableUniqueValidate
   {
        public Func<StageMaster, string> PrimaryKeySelector => primaryIndexSelector;
        readonly Func<StageMaster, string> primaryIndexSelector;


        public StageMasterTable(StageMaster[] sortedData)
            : base(sortedData)
        {
            this.primaryIndexSelector = x => x.Id;
            OnAfterConstruct();
        }

        partial void OnAfterConstruct();


        public StageMaster FindById(string key)
        {
            return FindUniqueCore(data, primaryIndexSelector, System.StringComparer.Ordinal, key, true);
        }
        
        public bool TryFindById(string key, out StageMaster result)
        {
            return TryFindUniqueCore(data, primaryIndexSelector, System.StringComparer.Ordinal, key, out result);
        }

        public StageMaster FindClosestById(string key, bool selectLower = true)
        {
            return FindUniqueClosestCore(data, primaryIndexSelector, System.StringComparer.Ordinal, key, selectLower);
        }

        public RangeView<StageMaster> FindRangeById(string min, string max, bool ascendant = true)
        {
            return FindUniqueRangeCore(data, primaryIndexSelector, System.StringComparer.Ordinal, min, max, ascendant);
        }


        void ITableUniqueValidate.ValidateUnique(ValidateResult resultSet)
        {
#if !DISABLE_MASTERMEMORY_VALIDATOR

            ValidateUniqueCore(data, primaryIndexSelector, "Id", resultSet);       

#endif
        }

#if !DISABLE_MASTERMEMORY_METADATABASE

        public static MasterMemory.Meta.MetaTable CreateMetaTable()
        {
            return new MasterMemory.Meta.MetaTable(typeof(StageMaster), typeof(StageMasterTable), "Stage",
                new MasterMemory.Meta.MetaProperty[]
                {
                    new MasterMemory.Meta.MetaProperty(typeof(StageMaster).GetProperty("Id")),
                    new MasterMemory.Meta.MetaProperty(typeof(StageMaster).GetProperty("Name")),
                    new MasterMemory.Meta.MetaProperty(typeof(StageMaster).GetProperty("Difficulty")),
                    new MasterMemory.Meta.MetaProperty(typeof(StageMaster).GetProperty("EnemyGroupId")),
                    new MasterMemory.Meta.MetaProperty(typeof(StageMaster).GetProperty("Exp")),
                    new MasterMemory.Meta.MetaProperty(typeof(StageMaster).GetProperty("ResourceId")),
                },
                new MasterMemory.Meta.MetaIndex[]{
                    new MasterMemory.Meta.MetaIndex(new System.Reflection.PropertyInfo[] {
                        typeof(StageMaster).GetProperty("Id"),
                    }, true, true, System.StringComparer.Ordinal),
                });
        }

#endif
    }
}